const response = {
  sa: {
    saved_params: {
      auction_name:
        "beliani.dk Natural rattan set, 2 seater + armchair, DOLCEDO CH",
      master_sa: "248905",
      offer_id: "289174",
      ShopMinusPercent: "30.03",
      ShopPriceComment: "",
      ShopRightOfReturn: "365",
      siteid: "903",
      snooze_date_shop: "",
      username: "Beliani DK",
      master_multi: null,
      ShopPrice: "13279.00",
      ShopHPrice: "18979.00",
      exclude_from_notification: "0",
      available: "1",
      available_date: "0000-00-00",
      available_weeks: "0",
      available_container_id: null,
      available_date_change_type: null,
      snooze_automatic_availability: "2022-07-21",
    },
    data: {
      id: "254340",
      inactive: "1",
      last_repeat: "0",
      repeat_days: "0",
      scheduled: null,
      nrepeats: "0",
      old: "1",
      stop_empty: "1",
      use_notsold: "0",
      marked: "0",
      shop_catalogue_id: "0",
      responsible_uname: "",
      export: "1",
      stop_empty_to_send: "0",
      merchant_id: null,
      template_id: "83",
      ebay_template_id: null,
      allegro_template_id: null,
      username: "Beliani DK",
      siteid: "903",
      offer_id: "289174",
      master_sa: "248905",
      master_multi: null,
      saved_group_id: null,
      saved_group_ordering: "0",
      auction_name:
        "beliani.dk Natural rattan set, 2 seater + armchair, DOLCEDO CH",
      duplicated_sa_id: null,
      ShopPrice: "13279.00",
      ShopHPrice: "18979.00",
      ShopPriceBlockContainer: null,
      ShopPriceBlockContainerDays: "0",
      main_assigned_category: null,
      main_assigned_group: null,
      available: "1",
      available_date: "0000-00-00",
      available_weeks: "0",
      available_container_id: null,
      available_date_change_type: null,
      snooze_automatic_availability: "2022-07-21",
      minava: "20",
    },
    buttons: {
      default_url: "loungesat-4-pers-rattan-natur-beige-dolcedo.html",
      lander_url: "loungesat-4-pers-rattan-natur-beige-dolcedo.landing",
      uk_url: "4-seater-rattan-sofa-set-beige-dolcedo.html",
      redirects: [],
      master_auction_name:
        "beliani.ch Gartenm\u00f6bel Set Rattan 4- Sitzer DOLCEDO helles Beige",
      buttons_log: {
        inactive: "on 2024-03-21 14:10:34 by Katarzyna Go\u015bciniec",
        old: "on 2024-03-21 14:12:10 by Katarzyna Go\u015bciniec",
      },
      search: {
        title: "SHOW IN SA PC",
        search_url:
          "https://www.prologistics.info/sa_price.php?seller_channel_id=4&country=DK&username=Beliani DK&shop=25&offer_filter_type%5B%5D=name&offer_name%5B%5D=DOLCEDO&warehouses_ids[]=234&active=0&fix=&show_sold_n=&show_with_filter_below_type=margin&show_with_margin_below_perc=0&show_with_filter_above_type=margin&show_minstock=1&recalc_shipping_costs=1&filter=select",
      },
    },
    editable_fields: [],
    id: 254340,
    checkbox: {
      title: 'Exclude from notification "BELOW 40%" ',
      checked: "0",
    },
    alert: ['Marked as "old".', "\u0421ategories not set"],
  },
};
